/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pollapp;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Nandu
 */
public class HomeScreen extends javax.swing.JFrame {

    String uname;
    String email;
    int noofqs=0;
    JTextField toptions[];
    JLabel loptions[];
    Socket cs;
    DataInputStream in;
    DataOutputStream out;
    int poll_id;
    /**
     * Creates new form HomeScreen
     */
    public HomeScreen(String uname,String email) {
        this.email=email;
        this.uname = uname;
        initCon();
        initComponents();
    }
    public void initCon(){
        try {
            cs = new Socket("localhost",1234);
            in = new DataInputStream(cs.getInputStream());
            out = new DataOutputStream(cs.getOutputStream());
        }catch(IOException e){}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        bjoin = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        twelcome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setVisible(false);
        jLabel3 = new javax.swing.JLabel();
        tpollIdjoin = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tques = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        optionpane = new javax.swing.JPanel();
        noofitems = new javax.swing.JComboBox<>();
        bcreatepoll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(0, 153, 255));

        jButton1.setText("Create Poll");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bjoin.setText("Join Poll");
        bjoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bjoinActionPerformed(evt);
            }
        });

        jButton3.setText("View Result");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        twelcome.setText("Welcome "+uname);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bjoin, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(twelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(twelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addGap(38, 38, 38)
                .addComponent(bjoin)
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel3.setText("Enter poll Id");

        tpollIdjoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpollIdjoinActionPerformed(evt);
            }
        });

        jButton2.setText("Join");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(tpollIdjoin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tpollIdjoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jButton2)
                .addContainerGap(283, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        tques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tquesActionPerformed(evt);
            }
        });
        jPanel1.add(tques);
        tques.setBounds(310, 50, 141, 22);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("Question ?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 50, 745, 22);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("Number of Options");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 100, 262, 22);

        jScrollPane1.setBackground(new java.awt.Color(0, 204, 204));
        jScrollPane1.setBorder(null);

        optionpane.setBackground(new java.awt.Color(0, 204, 204));
        optionpane.setLayout(null);
        jScrollPane1.setViewportView(optionpane);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 160, 405, 227);

        noofitems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        noofitems.setSelectedIndex(-1);
        noofitems.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                noofitemsItemStateChanged(evt);
            }
        });
        noofitems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofitemsActionPerformed(evt);
            }
        });
        jPanel1.add(noofitems);
        noofitems.setBounds(310, 100, 53, 22);

        bcreatepoll.setText("Create");
        bcreatepoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcreatepollActionPerformed(evt);
            }
        });
        jPanel1.add(bcreatepoll);
        bcreatepoll.setBounds(270, 420, 72, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 226, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);             // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bjoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjoinActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
//        jPanel1.revalidate();
//        jPanel1.repaint();
    }//GEN-LAST:event_bjoinActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tquesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tquesActionPerformed

    private void bcreatepollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcreatepollActionPerformed
        if(noofqs == 0){
            JOptionPane.showMessageDialog(this, "Please select the no of options!!!",
               "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(tques.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please type the question!!!",
               "Warning", JOptionPane.WARNING_MESSAGE);
                return;
        }
        for(int i=0;i<noofqs;i++){
            if(toptions[i].getText().equals("")){
                JOptionPane.showMessageDialog(this, "Please fill all the options!!!",
               "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        try {
            String str = "insert into tbl_poll(poll_question, poll_type, password, status) values('"+tques.getText()+"',  \"\",\"\","+1+")";
            out.writeUTF("poll_insert");
            out.writeUTF(str);
            poll_id = in.readInt();
            for(int i=0;i<noofqs;i++){
                str = "insert into tbl_options(poll_id, option_value) values('"+poll_id+"', '"+toptions[i].getText()+"')";
                out.writeUTF("insert");
                out.writeUTF(str);
            }
            JOptionPane.showMessageDialog(this, "Created Succesfully!!!");
            optionpane.removeAll();
            optionpane.revalidate();
            optionpane.repaint();
            noofqs = 0;
            tques.setText("");
            noofitems.setSelectedIndex(-1);
            
            
            
        } catch (IOException ex) {
            Logger.getLogger(HomeScreen.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        catch (Exception e) {
            System.out.println("Ex is"+e);
        
        }
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_bcreatepollActionPerformed

    private void noofitemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofitemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noofitemsActionPerformed

    private void noofitemsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_noofitemsItemStateChanged
        noofqs = Integer.parseInt(String.valueOf(noofitems.getSelectedItem()));
        optionpane.removeAll();
        optionpane.repaint();
        toptions = new JTextField[noofqs];
        loptions = new JLabel[noofqs];
        int y = 30;
        for(int i=0;i<noofqs;i++){
            loptions[i] = new JLabel("Option "+(i+1));
            toptions[i] = new JTextField();
            optionpane.add(loptions[i]);
            optionpane.add(toptions[i]);
            loptions[i].setBounds(50, y, 70, 16);
            toptions[i].setBounds(220, y, 90, 22);

            y = y+30;
        }
        optionpane.revalidate();
        optionpane.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_noofitemsItemStateChanged

    private void tpollIdjoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpollIdjoinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpollIdjoinActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            
            String str = "select * from tbl_poll where poll_id='"+tpollIdjoin.getText()+"'";
            out.writeUTF("select-poll");
            out.writeUTF(str);
            if(in.readBoolean()){
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Poll Not Found!!",
               "Warning", JOptionPane.WARNING_MESSAGE);
            }
            
        }catch (IOException ex) {
            Logger.getLogger(HomeScreen.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        catch (Exception e) {
            System.out.println("Ex is"+e);
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcreatepoll;
    private javax.swing.JButton bjoin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> noofitems;
    private javax.swing.JPanel optionpane;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTextField tpollIdjoin;
    private javax.swing.JTextField tques;
    private javax.swing.JLabel twelcome;
    // End of variables declaration//GEN-END:variables
}
